import type { Engine } from '../game/engine';
import type { ActionInput } from '../input/actions';
/** Display values only, sampled at most 12.5 Hz. Phase changes bypass the timer. */
export function hudSignature(
  engine: Engine,
  controls: ActionInput,
  guideStep: string,
) {
  const w = engine.world,
    p = w.player;
  return [
    w.phase,
    w.room.nodeId,
    w.room.index,
    w.room.name,
    w.wave,
    w.level,
    w.xp,
    Math.ceil(p.hp),
    p.maxHp,
    p.shield,
    p.dashCd.toFixed(1),
    p.qCd.toFixed(1),
    p.eCd.toFixed(1),
    p.dashCd > 0,
    p.qCd > 0,
    p.eCd > 0,
    w.bombCd > 0,
    Math.floor(w.elapsed),
    w.kills,
    w.reactionCount,
    w.boss?.hp,
    w.boss?.phase,
    w.fieldBuff,
    w.challengeTime.toFixed(1),
    w.weapon,
    w.forms.join(),
    w.cards.join(),
    w.rewards.map((c) => c.id).join(),
    w.rewardContext,
    w.campUsed.join(),
    w.campMessage,
    w.rerolls,
    w.banked,
    w.eventDone,
    w.settlement,
    Math.round(w.totalDamage),
    JSON.stringify(w.wallet),
    JSON.stringify(engine.save.meta),
    JSON.stringify(engine.save.settings),
    engine.save.checkpoint?.room.index,
    controls.connected,
    controls.lastDevice,
    engine.practice,
    guideStep,
  ].join('|');
}
