import { test, expect } from '@playwright/test';
test('DEV inspector steps real simulation, spawns Boss, grants once and draws overlays', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.addInitScript(() => localStorage.setItem('debug-sentinel', 'unchanged'));
  await page.goto('/dev/debugger');
  await expect(page.getByRole('heading', { name: 'Simulation debugger' })).toBeVisible();
  await page.getByRole('button', { name: 'Single tick' }).click();
  await expect(page.getByTestId('debug-tick')).toHaveText('1');
  await page.waitForTimeout(300);
  await expect(page.getByTestId('debug-tick')).toHaveText('1');
  await page.getByLabel('Debug enemy type').selectOption('warden');
  await page.getByRole('button', { name: 'Spawn enemy / Boss' }).click();
  await expect(page.getByTestId('debug-enemy')).toContainText('"kind": "warden"');
  await page.getByLabel('Debug protocol').selectOption('ice-shell');
  await page.getByRole('button', { name: 'Grant protocol' }).click();
  await page.getByRole('button', { name: 'Grant protocol' }).click();
  await expect(page.getByTestId('debug-hp')).toHaveText('160 / 160');
  await page.getByLabel('Debug weapon').selectOption('cannon');
  await page.getByLabel('hitboxes', { exact: true }).check();
  await page.getByLabel('grid', { exact: true }).check();
  await page.getByLabel('labels', { exact: true }).check();
  await page.getByLabel('Debug time scale').selectOption('2');
  await page.getByRole('button', { name: 'Resume simulation' }).click();
  await expect.poll(async () => Number(await page.getByTestId('debug-tick').innerText()), { timeout: 20000 }).toBeGreaterThan(180);
  await page.getByRole('button', { name: 'Pause simulation' }).click();
  await expect(page.getByLabel('Runtime diagnostics')).toContainText(/Grid [1-9]/);
  await page.keyboard.press('F3');
  await expect(page.getByLabel('Runtime diagnostics')).toBeHidden();
  await page.keyboard.press('F3');
  await expect(page.getByLabel('Runtime diagnostics')).toBeVisible();
  await page.screenshot({ path: 'outputs/qa/debugger.png', fullPage: true });
  expect(await page.evaluate(() => localStorage.getItem('debug-sentinel'))).toBe('unchanged');
  expect(errors).toEqual([]);
});
