import type { Element, Upgrade } from '../game/types';
export const ELEMENTS: Record<
  Element,
  {
    name: string;
    en: string;
    color: string;
    description: string;
    synergy: string;
  }
> = {
  fire: {
    name: '火焰',
    en: 'PYRE',
    color: '#ffb477',
    description: '点燃目标，以余烬吞没敌群。',
    synergy: '3 协议：燃烧伤害 +4 / 秒',
  },
  storm: {
    name: '雷电',
    en: 'VOLT',
    color: '#baa5ff',
    description: '在敌群间建立连锁电弧。',
    synergy: '3 协议：电弧额外连接 1 个目标',
  },
  frost: {
    name: '冰霜',
    en: 'RIME',
    color: '#90dbf4',
    description: '减速、穿透，让战场慢下来。',
    synergy: '3 协议：减速强度额外 +10%',
  },
  void: {
    name: '虚空',
    en: 'NULL',
    color: '#d2a2ec',
    description: '折弯弹道，牵引所有可能。',
    synergy: '3 协议：引力奇点冷却 −20%',
  },
  shift: {
    name: '跃迁',
    en: 'SHIFT',
    color: '#d0ed9e',
    description: '在闪避间隙，创造爆发窗口。',
    synergy: '3 协议：基础伤害 +4',
  },
};
type Row = [string, string, string, string, string, Upgrade['rarity']];
const groups: Record<Element, Row[]> = {
  fire: [
    [
      'fire-meteor',
      '赤核陨星',
      'CRIMSON MASS',
      '弹体变为缓慢的大型陨星；可叠加追踪、反弹与多发。',
      '伤害 ×1.65 · 射击间隔 ×1.4',
      'epic',
    ],
    [
      'fire-bloom',
      '星火胚芽',
      'SOLAR SEEDS',
      '主弹首次命中时裂出三枚继承元素的微型弹。微型弹不会再次分裂或触发反应。',
      '分裂 3 发 · 每发 28% 伤害',
      'rare',
    ],
    [
      'fire-ember',
      '余烬协议',
      'EMBER SCRIPT',
      '奥术弹点燃敌人，持续 3 秒。',
      '燃烧 8 伤害 / 秒',
      'common',
    ],
    [
      'fire-fuel',
      '恒星燃料',
      'STAR FUEL',
      '强化已激活的燃烧，让余烬更具杀伤。',
      '燃烧提升至 18 伤害 / 秒',
      'rare',
    ],
    [
      'fire-funeral',
      '焚毁回执',
      'FUNERAL BLOOM',
      '直接攻击击杀敌人时，引爆附近敌人。',
      '爆炸 24 伤害 · 半径 100',
      'rare',
    ],
    [
      'fire-split',
      '三重星火',
      'TRIPLE SUN',
      '奥术弹变为三发扇射，每发伤害降低。',
      '3 发弹体 · 单发伤害 ×75%',
      'epic',
    ],
    [
      'fire-blast',
      '熔火弹头',
      'MOLTEN SHELL',
      '每次直接命中额外溅射周围目标。',
      '溅射 25% 伤害 · 半径 65',
      'epic',
    ],
    [
      'fire-dash',
      '燃烧轨迹',
      'CINDER WAKE',
      '相位跃迁会留下持续燃烧的轨迹。',
      '路径灼烧 · 持续 1.5 秒',
      'common',
    ],
  ],
  storm: [
    [
      'storm-lance',
      '贯星光矛',
      'ASTRAL LANCE',
      '高速光矛穿过敌群，仍可叠加多发与反弹；射击间隔增加。',
      '穿透 +3 · 弹速 ×2.4 · 间隔 ×1.35',
      'epic',
    ],
    [
      'storm-familiar',
      '浮游使魔',
      'CHOIR WISP',
      '一枚使魔围绕你，每 0.7 秒向准星射击，继承弹道与元素状态。',
      '辅助射击 45% 伤害 · 不触发派生反应',
      'rare',
    ],
    [
      'storm-arc',
      '电弧引擎',
      'ARC ENGINE',
      '直接命中有 33% 概率将电弧传至附近敌人。',
      '连锁 2 个目标 · 48% 伤害',
      'common',
    ],
    [
      'storm-conduct',
      '并联回路',
      'PARALLEL CIRCUIT',
      '增加电弧跳跃次数，覆盖更大敌群。',
      '连锁目标 +2',
      'rare',
    ],
    [
      'storm-static',
      '静电积蓄',
      'STATIC MEMORY',
      '更频繁地激活电弧引擎。',
      '电弧触发概率 33% → 53%',
      'rare',
    ],
    [
      'storm-critical',
      '临界电压',
      'CRITICAL VOLTAGE',
      '暴击率提升，暴击会电击目标周围敌人。',
      '暴击 +22% · 40% 范围伤害',
      'epic',
    ],
    [
      'storm-surge',
      '超频脉冲',
      'OVERCLOCK',
      '缩短基础射击间隔。',
      '射击间隔 −22%',
      'common',
    ],
    [
      'storm-needle',
      '导电针阵',
      'CONDUCTIVE NEEDLE',
      '奥术弹穿透更多目标，让电弧沿弹道传播。',
      '弹体穿透 +2',
      'rare',
    ],
  ],
  frost: [
    [
      'frost-wave',
      '蜿蜒频谱',
      'SERPENT WAVE',
      '弹体沿波形前进，可叠加追踪、反弹和环绕。',
      '波动弹道 · 横向覆盖',
      'common',
    ],
    [
      'frost-fan',
      '碎星扇面',
      'SHARD FAN',
      '每次射击增加两枚弹体，降低单发伤害。',
      '弹体 +2 · 单发伤害 ×70%',
      'epic',
    ],
    [
      'ice-touch',
      '冰霜编码',
      'FROST CODE',
      '直接命中施加寒冷，持续 2.5 秒。',
      '敌人移速 −35%',
      'common',
    ],
    [
      'ice-brittle',
      '脆化解析',
      'BRITTLE LOGIC',
      '对寒冷目标造成更多伤害。',
      '对减速目标伤害 +25%',
      'rare',
    ],
    [
      'ice-shatter',
      '碎晶连锁',
      'SHATTER SIGNAL',
      '直接击杀寒冷目标时，伤害并减速附近敌人。',
      '碎裂 20 伤害 · 半径 120',
      'epic',
    ],
    [
      'ice-pierce',
      '永冻长针',
      'GLACIAL NEEDLE',
      '提高基础伤害，奥术弹穿透一名敌人。',
      '穿透 +1 · 伤害 +4',
      'rare',
    ],
    [
      'ice-shell',
      '晶体装甲',
      'CRYSTAL SHELL',
      '强化生命容器，并恢复新增生命。',
      '最大生命 +40 · 恢复 40',
      'common',
    ],
    [
      'ice-prism',
      '棱镜反射',
      'PRISMATIC ECHO',
      '子弹遇到竞技场边界会反射。',
      '弹体反弹 2 次',
      'rare',
    ],
  ],
  void: [
    [
      'void-orbit',
      '微型星系',
      'LITTLE COSMOS',
      '主弹先围绕你旋转，再飞向敌群；环绕半径逐渐扩大。',
      '星轨弹道 · 穿透 +2 · 间隔 ×1.2',
      'epic',
    ],
    [
      'void-return',
      '逆因果回旋',
      'RETURN VECTOR',
      '弹体飞行后折返至你身边；无法反弹的边界提前返航，保留命中记录。',
      '回旋弹道 · 单发伤害 ×90%',
      'rare',
    ],
    [
      'void-seek',
      '引力偏移',
      'GRAVITY BIAS',
      '奥术弹逐渐弯向最近的敌人。',
      '追踪弹道',
      'common',
    ],
    [
      'void-horizon',
      '事件视界',
      'EVENT HORIZON',
      '扩大引力奇点的牵引和伤害范围。',
      '奇点半径 115 → 155',
      'rare',
    ],
    [
      'void-execute',
      '终止指令',
      'TERMINAL COMMAND',
      '对低生命目标造成更高伤害。',
      '目标低于 25% 生命时伤害 +50%',
      'epic',
    ],
    [
      'void-leech',
      '暗质回收',
      'DARK HARVEST',
      '每击杀一个敌人，回收生命。',
      '每次击杀恢复 1 生命',
      'rare',
    ],
    [
      'void-singularity',
      '坍缩时钟',
      'COLLAPSE CLOCK',
      '缩短引力奇点的冷却。',
      'E 冷却 −35%',
      'common',
    ],
    [
      'void-echo',
      '因果回响',
      'CAUSAL ECHO',
      '更频繁地释放湮灭脉冲，提高基础伤害。',
      'Q 冷却 −35% · 伤害 +4',
      'rare',
    ],
  ],
  shift: [
    [
      'shift-echo',
      '镜像裂雨',
      'MIRROR RAIN',
      '每次 Dash 从起点向八个方向放出元素弹幕。',
      '8 枚次生弹 · 每枚 45% 伤害',
      'epic',
    ],
    [
      'shift-rear',
      '双向因果',
      'JANUS VECTOR',
      '射击同时向背后发出一枚次生弹，继承弹道和元素状态。',
      '背向弹体 · 65% 伤害',
      'rare',
    ],
    [
      'shift-quick',
      '快速重编译',
      'QUICK COMPILE',
      '缩短相位跃迁的冷却。',
      'Dash 冷却 −30%',
      'common',
    ],
    [
      'shift-shield',
      '相位护盾',
      'PHASE GUARD',
      '每次闪避时生成护盾，吸收之后的伤害。',
      'Dash 获得 12 护盾 · 上限 30',
      'rare',
    ],
    [
      'shift-nova',
      '跃迁新星',
      'SHIFT NOVA',
      '闪避起点爆发冲击波，伤害周围敌人。',
      '范围伤害 28 · 半径 120',
      'epic',
    ],
    [
      'shift-ice',
      '零度闪移',
      'ZERO SHIFT',
      '每次闪避时，减速附近敌人。',
      '附近敌人减速 35% · 持续 3 秒',
      'rare',
    ],
    [
      'shift-reload',
      '越界射击',
      'PHASE RELOAD',
      '闪避后短时间内，射击速度翻倍。',
      'Dash 后 0.7 秒射速 ×2',
      'rare',
    ],
    [
      'shift-stride',
      '轻量化躯壳',
      'LIGHT FRAME',
      '提高移动速度，更轻松地调整射击位置。',
      '移动速度 +18%',
      'common',
    ],
  ],
};
export const CARDS: Upgrade[] = Object.entries(groups).flatMap(
  ([element, rows]) =>
    rows.map(([id, name, en, description, preview, rarity]) => ({
      id,
      name,
      en,
      description,
      preview,
      rarity,
      element: element as Element,
      icon: element,
    })),
);
export const REQUIREMENTS: Record<string, string> = {
  'fire-fuel': 'fire-ember',
  'storm-conduct': 'storm-arc',
  'storm-static': 'storm-arc',
  'ice-brittle': 'ice-touch',
  'ice-shatter': 'ice-touch',
};
